GARMIN_BRIDGE_NORMALIZATIONS: dict[tuple[str, str], str | None] = {
    ("sleeps", "get_sleep_data"): "sleeps",
    ("dailies", "get_stats"): "dailies",
    ("heart_rates", "get_heart_rates"): "dailies",
    ("hrv", "get_hrv_data"): "hrv",
    ("pulse_ox", "get_spo2_data"): "pulse_ox",
    ("respiration", "get_respiration_data"): "respiration",
    ("body_compositions", "get_body_composition"): "body_compositions",
    ("stress_details", "get_stress_data"): "stress_details",
    ("body_battery", "get_body_battery"): "stress_details",
    ("blood_pressures", "get_blood_pressure"): "blood_pressures",
    ("skin_temperature", "get_skin_temperature"): "skin_temperature",
    ("user_metrics", "get_max_metrics"): "user_metrics",
    ("fitness_age", "get_fitnessage_data"): "user_metrics",
    ("training_readiness", "get_training_readiness"): "training_readiness",
    ("training_status", "get_training_status"): None,
    ("training_load", "get_training_load_focus"): None,
    ("activities", "get_activities_by_date"): "activities",
    ("activity_details", "get_activity"): "activity_details",
    ("activity_laps", "get_activity_splits"): None,
    ("activity_routes", "get_activity_gps_data"): None,
    ("devices", "get_devices"): None,
}
